### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by veggiemonk** [kristianmandrup/slush-markoa#1]
```
slush markoa
 Slush markoa generator: v.0.5.7 
module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-print'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-markoa/layout/index.js:8:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

`gulp-print` is not found.

```
❯ npm -v
3.7.2
❯ node -v
v5.6.0

```

**Comment by kristianmandrup** [comment]
https://www.npmjs.com/package/gulp-print

Did you do `npm install`?

**Comment by veggiemonk** [comment]
Yes ! That is why I post it here. Sorry for the short preview message.

```
❯ npm install -g slush slush-markoa
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/slush -> /usr/local/lib/node_modules/slush/bin/slush.js
/usr/local/lib
├── slush@1.1.1 
└── slush-markoa@0.5.7 

❯ slush markoa
 Slush markoa generator: v.0.5.7 
module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-print'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/slush-markoa/layout/index.js:8:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

I kid you not, I cannot understand what is the problem...
And I have the same error with node 4.3.0 and npm 3.7.2

**Comment by kristianmandrup** [comment]
Just tried on my system. 

``` bash
14:40 $ npm install -g slush slush-markoa
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/slush -> /usr/local/lib/node_modules/slush/bin/slush.js
/usr/local/lib
├─┬ slush@1.1.1 
│ ├─┬ chalk@0.4.0 
│ │ ├── ansi-styles@1.0.0 
│ │ ├── has-color@0.1.7 
...

14:41 $ node -v
v5.5.0
14:44 $ npm -v
3.3.12

14:44 $ slush markoa

module.js:341
    throw err;
    ^

Error: Cannot find module 'gulp-print'

    at Object.<anonymous> (/usr/local/lib/node_modules/slush-markoa/layout/index.js:8:13)

```

Error must be here!!! `slush-markoa/layout/index.js:8:13`
Problem is that `gulp-print` is not listed as dependency in `package.json`

I'm not really on Node.js anymore. I've since switched to Clojure and ClojureScript :)
To me, Java, Javascript and Node.js are just runtimes with some useful libs ...

However Marko, Markoa etc. are very powerful for first time rendering in a multi-tiered client/server architecture!

**Comment by kristianmandrup** [comment]
I'm on it. Give me 5 mins

**Comment by kristianmandrup** [comment]
Fixed now with version 0.6.0

**Comment by veggiemonk** [comment]
@kristianmandrup Yeah! Thank you! It is cool you fixed it. Dependency management is really something, isn't it? :D

Clojure and ClojureScript would be the next languages to use. So much flexibility in the code, it's amazing what you can accomplish once you see through the `( )`. Lucky you.
How long did it took you to be at ease with it? Where did you start ? On what project?
I know I ask too many questions but it's not often I got to ask those kind of questions.
I apologize for any inconvenience. :relieved:

**Comment by kristianmandrup** [comment]
I'm happy it works now!

I'm still only getting into Clojure. I tried about 1 year ago, but felt ClojureScript was still a bit too immature with regards to javascript interop (module loading) and f.ex for use with React Native etc. Now those concerns have been resolved and future is looking bright! 

I' recommend starting with the free online book [Clojure for the Brave and True](http://www.braveclojure.com), super funny!!! Reminds me of reading a similar crazy/legendary book when I first got into ruby :)

**Comment by veggiemonk** [comment]
The first sentences of the book

> Deep in your innermost being, you’ve always known you were destined to learn Clojure. Every time you held your keyboard aloft, crying out in anguish over an incomprehensible class hierarchy; every time you lay awake at night, disturbing your loved ones with sobs over a mutation-induced heisenbug; every time a race condition caused you to pull out more of your ever-dwindling hair, some secret part of you has known that _there has to be a better way_.

Already laughing! so much truth in it!
Thanks a lot. Really appreciated.

**Comment by kristianmandrup** [comment]
haha :) You will never look at programming quite the same again... enough of OOP and mutation hell!!!

**Comment by veggiemonk** [comment]
Amen!

---

Julien

**Comment by kristianmandrup** [comment]
For clojurescript, this looks like a pretty good blog that gives a nice overview...

http://squirrel.pl/blog/tag/clojurescript/
